"use client";

import { Brain, Sparkles, TrendingUp } from "lucide-react";

export default function AIInsights() {
  return (
    <div className="rounded-3xl border border-cyan-500/20 bg-[#0B1220] p-6">

      <div className="flex items-center gap-3">

        <Brain className="text-cyan-400" size={30} />

        <div>

          <h2 className="text-xl font-bold text-white">
            AI INSIGHTS
          </h2>

          <p className="text-gray-400 text-sm">
            Recommendations generated by AI
          </p>

        </div>

      </div>

      <div className="mt-8 space-y-5">

        <div className="rounded-2xl bg-white/5 p-4">

          <div className="flex items-center gap-3">

            <TrendingUp className="text-green-400" />

            <p className="text-white font-semibold">
              Viral Potential
            </p>

          </div>

          <p className="mt-2 text-gray-400 text-sm">
            Your latest video has high engagement potential.
          </p>

        </div>

        <div className="rounded-2xl bg-white/5 p-4">

          <div className="flex items-center gap-3">

            <Sparkles className="text-cyan-400" />

            <p className="text-white font-semibold">
              AI Recommendation
            </p>

          </div>

          <p className="mt-2 text-gray-400 text-sm">
            Publish between 19:00 and 21:00 to maximize reach.
          </p>

        </div>

      </div>

    </div>
  );
}