export type SEOResult = {
  title: string;
  description: string;
  keywords: string[];
  hashtags: string[];
};

export function generateSEO(topic: string): SEOResult {
  return {
    title: `${topic} | Complete AI Guide 2026`,

    description: `
Learn everything about ${topic}.

Generated by VYRO AI Director.

Professional content optimized for YouTube,
TikTok, Instagram and Facebook.
`.trim(),

    keywords: [
      topic,
      "AI",
      "Video",
      "Content Creator",
      "Marketing",
      "YouTube",
      "TikTok",
      "Instagram",
      "Viral",
      "VYRO AI",
    ],

    hashtags: [
      "#AI",
      "#VYRO",
      "#VideoAI",
      "#Creator",
      "#Content",
      "#Marketing",
      "#YouTube",
      "#TikTok",
      "#Instagram",
      "#Viral",
    ],
  };
}